name: Node.js CI

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:
  lint:
    name: Lint Packages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Main Dependencies
      run: npm install
    - name: Run the linter
      run: npm run lint
