name: Lint

on:
  push:
    branches: [ development, master ]
  pull_request:
    branches: [ development, master ]

jobs:
  lint-site:
    name: Lint React Site Code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Main Dependencies
      run: npm install
    - name: Lint the React Site
      run: npm run lint

  lint-function:
    name: Lint Functions Code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Main Dependencies
      run: npm install
      working-directory: functions
    - name: Lint the React Site
      run: npm run lint
      working-directory: functions

  build:
    name: Build Code for Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@master
    - name: Install Main Dependencies
      run: npm install
    - name: Build the React site
      run: npm run build
